### ISSUE TITLE
Visualization: Add adapter for speech

### ISSUE THREAD

**Issue by ekaszubski** [semio-robotics/semio_ros#34]
- Show speech output above closest person's head

**Comment by ekaszubski** [comment]
Implementing in #36

**Comment by ekaszubski** [comment]
@rossmead Can you clarify the desired behavior for this visualization in terms of the `SpeechRecognition` [messages](https://github.com/semio-robotics/semio_msgs_ros/tree/next/msg)? The adapter will receive `SpeechRecognitionResultList` messages.

**Comment by rossmead** [comment]
Take the top hit from the speech rec list and place it above the head of the closest person (this will hopefully change someday if we can do speaker localization).

If possible, center align (horizontally) the text so it expands out as a person speaks. You might also have a word wrap at some number of characters (maybe 50? whatever looks good), though not sure how hard that is.

If possible, bottom align (vertically) the text so that it expands up as the person speaks.

Maybe add the likelihood with no decimal places -- up to two whole numbers and a "%" inside of square brackets in front of the text. Could color the text based on the color of the speaker, the state of the recognition (e.g., recognizing vs. done recognizing), or the likelihood -- open to ideas.

Have the text fade out after some time (5 seconds?).

Let me know if you have any other thoughts. Thanks! :-)

**Comment by rossmead** [comment]
To clarify, "top hit" = the output of the speech rec system with the highest likelihood. Preferably while it's being recognized (the "recognizing" phase), or worst case the final recognition (probably an easier place to start).

**Comment by ekaszubski** [comment]
Implemented in #36
